### ISSUE TITLE
DSSP.py returns AssertionError

### ISSUE THREAD

**Issue by neb9** [graik/biskit#12]
I've now switched over to the latest master. However, on 1AM7, just straight up doing

```
m = PDBModel(file)
d = Dssp(m)
sec = d.run()
```
breaks, returning:

```
File "/usr/local/lib/python2.7/dist-packages/biskit-2.4.3-py2.7.egg/Biskit/Executor.py", line 557, in run
    self.finish()
  File "/usr/local/lib/python2.7/dist-packages/biskit-2.4.3-py2.7.egg/Biskit/DSSP.py", line 240, in finish
    self.result = self.parse_result( )
  File "/usr/local/lib/python2.7/dist-packages/biskit-2.4.3-py2.7.egg/Biskit/DSSP.py", line 230, in parse_result
    assert len(secStruc) == self.model.lenResidues()
AssertionError
```

**Comment by neb9** [comment]
This seems to happen with a number of PBD files which were OK before.

**Comment by graik** [comment]
Outch. OK, so it looks like the "or" was not a bug after all. I didn't write this code so there was a bit of guess work involved. It worked for the only three cases I looked at. This means the DSSP output parsing has to be re-visited. I haven't got time at all for the next three days or so, at least. Perhaps you can have a look? 

Adding one of your failing structures as an additional test case would be a start. The parsing doesn't look that complicated actually. The code is iterating in parallel over (1) the output list of DSSP "residues" and (2) the actual list of PDB residues. Problem is that the two are not the same and DSSP is e.g. reporting output lines for chain ends so the code tries to compensate for that. And somehow this now occasionally fails. The question is when and how.
/Raik

**Comment by graik** [comment]
change reverted, the original issue persists.
